version: "3.3"
services:
  app:
    container_name: react-remote-terminal
    restart: always
    build: .
    environment:
      PORT: 3000
      SERVER_URL: "http://localhost:8080"
    ports:
      - "3000:3000"
